# Generated by Gemini 3.1 Pro (High)
import numpy as np
import pandas as pd

# --- Encoding Functions ---

def label_encode(series):
    """
    Generated by Gemini 3.1 Pro (High)
    Encodes categorical features with integer labels.
    """
    unique_categories = list(dict.fromkeys(series.dropna()))
    mapping = {cat: idx for idx, cat in enumerate(unique_categories)}
    encoded_series = series.map(lambda x: mapping.get(x, -1))
    return encoded_series, mapping

def one_hot_encode(series):
    """
    Generated by Gemini 3.1 Pro (High)
    One-hot encodes a categorical feature.
    """
    col_name = series.name if series.name else 'feature'
    unique_categories = sorted(series.dropna().unique())
    ohe_dict = {
        f"{col_name}_{cat}": (series == cat).astype(int)
        for cat in unique_categories
    }
    return pd.DataFrame(ohe_dict)


# --- Distance Metrics ---

def minkowski_distance(vector_a, vector_b, p):
    """
    Generated by Gemini 3.1 Pro (High)
    Calculates the generalized Minkowski distance between two vectors.
    """
    vec_a = np.array(vector_a, dtype=float)
    vec_b = np.array(vector_b, dtype=float)

    if vec_a.shape != vec_b.shape:
        raise ValueError(f"Vector shapes do not match: {vec_a.shape} vs {vec_b.shape}")
    if p < 1:
        raise ValueError("Parameter p must be >= 1")

    return float(np.sum(np.abs(vec_a - vec_b) ** p) ** (1.0 / p))


# --- Statistical Functions ---

def compute_mean(data):
    """
    Generated by Gemini 3.1 Pro (High)
    Computes the mean of an array.
    """
    arr = np.array(data, dtype=float)
    if len(arr) == 0:
        raise ValueError("Empty array")
    return float(np.sum(arr) / len(arr))


def compute_variance(data, ddof=0):
    """
    Generated by Gemini 3.1 Pro (High)
    Computes the variance of an array.
    """
    arr = np.array(data, dtype=float)
    mean_val = compute_mean(arr)
    return float(np.sum((arr - mean_val) ** 2) / (len(arr) - ddof))


def compute_std(data, ddof=0):
    """
    Generated by Gemini 3.1 Pro (High)
    Computes the standard deviation of an array.
    """
    return float(np.sqrt(compute_variance(data, ddof=ddof)))


def dataset_statistics(matrix):
    """
    Generated by Gemini 3.1 Pro (High)
    Computes means, variances, and stds for each column in a 2D matrix.
    """
    mat = np.array(matrix, dtype=float)
    num_features = mat.shape[1]
    means = [compute_mean(mat[:, j]) for j in range(num_features)]
    variances = [compute_variance(mat[:, j]) for j in range(num_features)]
    stds = [compute_std(mat[:, j]) for j in range(num_features)]
    return means, variances, stds


# --- K-Means Clustering ---

def kmeans(data_matrix, k, max_iterations=100, tolerance=1e-4, random_seed=42):
    """
    Generated by Gemini 3.1 Pro (High)
    Performs K-Means clustering.
    """
    data = np.array(data_matrix, dtype=float)
    num_samples, num_features = data.shape
    
    rng = np.random.default_rng(random_seed)
    centroids = data[rng.choice(num_samples, size=k, replace=False)].copy()
    labels = np.zeros(num_samples, dtype=int)
    inertia_history = []

    for iteration in range(max_iterations):
        # Assign clusters
        for i in range(num_samples):
            dists = [minkowski_distance(data[i], c, p=2) for c in centroids]
            labels[i] = int(np.argmin(dists))

        # Update centroids
        new_centroids = np.zeros((k, num_features))
        for c_idx in range(k):
            members = data[labels == c_idx]
            if len(members) == 0:
                new_centroids[c_idx] = data[rng.choice(num_samples)]
            else:
                new_centroids[c_idx] = [compute_mean(members[:, j]) for j in range(num_features)]

        # Calculate inertia
        inertia = sum(minkowski_distance(data[i], new_centroids[labels[i]], p=2) ** 2 for i in range(num_samples))
        inertia_history.append(inertia)

        # Check for convergence
        shift = max(minkowski_distance(centroids[c], new_centroids[c], p=2) for c in range(k))
        centroids = new_centroids

        if shift < tolerance:
            break

    return labels, centroids, inertia_history[-1], inertia_history

