# Generated by Gemini 3.1 Pro (High)
import unittest
import numpy as np
import pandas as pd
from lab4 import label_encode, one_hot_encode, minkowski_distance, compute_mean, compute_variance, compute_std, kmeans

class TestLab4Functions(unittest.TestCase):
    
    def test_label_encode(self):
        # Generated by Gemini 3.1 Pro (High)
        s = pd.Series(['apple', 'banana', 'apple', 'cherry'])
        encoded, mapping = label_encode(s)
        self.assertEqual(mapping['apple'], 0)
        self.assertEqual(mapping['banana'], 1)
        self.assertEqual(mapping['cherry'], 2)
        self.assertEqual(list(encoded), [0, 1, 0, 2])

    def test_one_hot_encode(self):
        # Generated by Gemini 3.1 Pro (High)
        s = pd.Series(['A', 'B', 'A'], name='Letter')
        ohe = one_hot_encode(s)
        self.assertIn('Letter_A', ohe.columns)
        self.assertIn('Letter_B', ohe.columns)
        self.assertEqual(list(ohe['Letter_A']), [1, 0, 1])
        self.assertEqual(list(ohe['Letter_B']), [0, 1, 0])

    def test_minkowski_distance(self):
        # Generated by Gemini 3.1 Pro (High)
        v1 = [0, 0]
        v2 = [3, 4]
        # p=1 (Manhattan)
        self.assertAlmostEqual(minkowski_distance(v1, v2, 1), 7.0)
        # p=2 (Euclidean)
        self.assertAlmostEqual(minkowski_distance(v1, v2, 2), 5.0)

    def test_compute_mean(self):
        # Generated by Gemini 3.1 Pro (High)
        data = [2, 4, 4, 4, 5, 5, 7, 9]
        self.assertAlmostEqual(compute_mean(data), 5.0)

    def test_compute_variance(self):
        # Generated by Gemini 3.1 Pro (High)
        data = [2, 4, 4, 4, 5, 5, 7, 9]
        # Population variance (ddof=0)
        self.assertAlmostEqual(compute_variance(data, ddof=0), 4.0)
    
    def test_compute_std(self):
        # Generated by Gemini 3.1 Pro (High)
        data = [2, 4, 4, 4, 5, 5, 7, 9]
        self.assertAlmostEqual(compute_std(data, ddof=0), 2.0)
        
    def test_kmeans(self):
        # Generated by Gemini 3.1 Pro (High)
        # Create clear distinct clusters
        data = np.array([
            [1, 1], [1, 2], [2, 1], # Cluster 1
            [10, 10], [10, 11], [11, 10] # Cluster 2
        ])
        labels, centroids, inertia, history = kmeans(data, k=2, random_seed=42)
        
        # Check that the two clusters were correctly separated
        # We don't know if cluster 1 is label 0 or 1, but they should be grouped
        c1_labels = labels[0:3]
        c2_labels = labels[3:6]
        
        # All elements in c1 should have same label
        self.assertEqual(len(set(c1_labels)), 1)
        # All elements in c2 should have same label
        self.assertEqual(len(set(c2_labels)), 1)
        # Labels for c1 and c2 should be different
        self.assertNotEqual(c1_labels[0], c2_labels[0])

if __name__ == '__main__':
    unittest.main()
